name: CI - Chạy test

#Điều kiện chạy pipeline
#Đơn giản: trigger chạy test khi push code lên github
#Thực tế:
#Tạo pull request -> trigger pipeline
#Merge pull request -> trigger pipeline
on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]
jobs:
  test: #define step test
    #Chọn môi trường chạy
    runs-on: ubuntu-latest
    steps:
      #B1: Clone source từ github về môi trường chạy
      - name: Checkout code
        uses: actions/checkout@v4
      #B2: Setup nodejs
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm" #cache này giúp lưu lại các package đã cài đặt để lần chạy sau nhanh hơn
      #B3: Cài đặt các package
      - name: Install dependencies
        run: npm install
      #B4: Cài browser có sẵn của Playwright
      #--with-deps: cài thêm các dependencies cần thiết để chạy browser
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      #B5: Chạy test
      - name: Run tests
        run: npx playwright test
